/**
 * Mapping from subdivision names to their country code.
 * Used to properly identify subdivision flags vs national flags.
 */
export const subdivisionToCountryCode: Record<string, string> = {
  // Germany
  "Bavaria": "DE",
  "Baden-Württemberg": "DE",
  "Berlin": "DE",
  "Brandenburg": "DE",
  "Bremen": "DE",
  "Hamburg": "DE",
  "Hesse": "DE",
  "Lower Saxony": "DE",
  "Mecklenburg-Vorpomerania": "DE",
  "North Rhine-Westphalia": "DE",
  "Rhineland-Palatinate": "DE",
  "Saarland": "DE",
  "Saxony": "DE",
  "Saxony-Anhalt": "DE",
  "Schleswig-Holstein": "DE",
  "Thuringia": "DE",

  // USA
  "Hawaii": "US",
  "Alabama": "US",
  "Alaska": "US",
  "Arizona": "US",
  "Arkansas": "US",
  "California": "US",
  "Colorado": "US",
  "Connecticut": "US",
  "Delaware": "US",
  "Florida": "US",
  // "Georgia": "US", -- REMOVED: ambiguous with Georgia (country), use full name if needed
  "Idaho": "US",
  "Illinois": "US",
  "Indiana": "US",
  "Iowa": "US",
  "Kansas": "US",
  "Kentucky": "US",
  "Louisiana": "US",
  "Maine": "US",
  "Maryland": "US",
  "Massachusetts": "US",
  "Michigan": "US",
  "Minnesota": "US",
  "Mississippi": "US",
  "Missouri": "US",
  "Montana": "US",
  "Nebraska": "US",
  "Nevada": "US",
  "New Hampshire": "US",
  "New Jersey": "US",
  "New Mexico": "US",
  "New York": "US",
  "North Carolina": "US",
  "North Dakota": "US",
  "Ohio": "US",
  "Oklahoma": "US",
  "Oregon": "US",
  "Pennsylvania": "US",
  "Rhode Island": "US",
  "South Carolina": "US",
  "South Dakota": "US",
  "Tennessee": "US",
  "Texas": "US",
  "Utah": "US",
  "Vermont": "US",
  "Virginia": "US",
  "Washington": "US",
  "West Virginia": "US",
  "Wisconsin": "US",
  "Wyoming": "US",
  "District of Columbia": "US",

  // France
  "Normandy": "FR",
  "Île-de-France": "FR",
  "Provence-Alpes-Côte d'Azur": "FR",
  "Auvergne-Rhône-Alpes": "FR",
  "Bourgogne-Franche-Comté": "FR",
  "Brittany": "FR",
  "Hauts-de-France": "FR",
  "Grand Est": "FR",
  "New Aquitaine": "FR",
  "Occitanie": "FR",
  "Pays de la Loire": "FR",
  "Centre-Val de Loire": "FR",
  "Corsica": "FR",

  // Spain
  "Andalusia": "ES",
  "Aragon": "ES",
  "Asturias": "ES",
  "Balearic Islands": "ES",
  "Basque Country": "ES",
  "the Basque Country": "ES",
  "Canary Islands": "ES",
  "Cantabria": "ES",
  "Castile and León": "ES",
  "Castilla-La Mancha": "ES",
  "Catalonia": "ES",
  "Catalogna Indipendente": "ES",
  "Extremadura": "ES",
  "Galicia": "ES",
  "La Rioja": "ES",
  "Madrid": "ES",
  "Murcia": "ES",
  "Navarre": "ES",
  "Valencia": "ES",
  "the Valencian Community": "ES",
  "Siviglia": "ES",
  "Bilbao": "ES",

  // Italy
  "Aosta Valley": "IT",
  "Piedmont": "IT",
  "Liguria": "IT",
  "Lombardy": "IT",
  "Trentino-Alto Adige": "IT",
  "Veneto": "IT",
  "Friuli-Venezia Giulia": "IT",
  "Emilia-Romagna": "IT",
  "Tuscany": "IT",
  "Umbria": "IT",
  "Marche": "IT",
  "Lazio": "IT",
  "Abruzzi": "IT",
  "Molise": "IT",
  "Campania": "IT",
  "Basilicata": "IT",
  "Calabria": "IT",
  "Sicily": "IT",
  "Sardinia": "IT",
  "Trieste": "IT",
  "Venice": "IT",
  "Pisa": "IT",
  "Elba": "IT",

  // Czech Republic
  "Prague": "CZ",
  "Central Bohemian Region": "CZ",
  "South Bohemian Region": "CZ",
  "Plzeň Region": "CZ",
  "Karlovy Vary Region": "CZ",
  "Ústí nad Labem Region": "CZ",
  "Liberec Region": "CZ",
  "Hradec Králové Region": "CZ",
  "Pardubice Region": "CZ",
  "Moravian-Silesian Region": "CZ",
  "Olomouc Region": "CZ",
  "Zlín Region": "CZ",
  "South Moravian Region": "CZ",
  "Bohemia": "CZ",
  "Moravia": "CZ",
  "Czech Silesia": "CZ",

  // UK
  "Scotland": "GB",
  "Reale Scozzese": "GB",
  "Wales": "GB",

  // Canada
  "Alberta": "CA",
  "British Columbia": "CA",
  "Manitoba": "CA",
  "New Brunswick": "CA",
  "Newfoundland and Labrador": "CA",
  "Northwest Territories": "CA",
  "Nova Scotia": "CA",
  "Nunavut": "CA",
  "Ontario": "CA",
  "Prince Edward Island": "CA",
  "Quebec": "CA",
  "Saskatchewan": "CA",
  "Yukon": "CA",

  // Austria
  "Burgenland": "AT",
  "Carinthia": "AT",
  "Lower Austria": "AT",
  "Salzburg": "AT",
  "Styria": "AT",
  "Tyrol": "AT",
  "Upper Austria": "AT",
  "Vienna": "AT",
  "Vorarlberg": "AT",

  // Brazil
  "Acre": "BR",
  "Alagoas": "BR",
  "Amapá": "BR",
  "Amazonas": "BR",
  "Bahia": "BR",
  "Ceará": "BR",
  "Federal District": "BR",
  "Espírito Santo": "BR",
  "Goiás": "BR",
  "Maranhão": "BR",
  "Mato Grosso": "BR",
  "Mato Grosso do Sul": "BR",
  "Minas Gerais": "BR",
  "Pará": "BR",
  "Paraíba": "BR",
  "Paraná": "BR",
  "Pernambuco": "BR",
  "Piauí": "BR",
  "Rio de Janeiro": "BR",
  "Rio Grande do Norte": "BR",
  "Rio Grande do Sul": "BR",
  "Rondônia": "BR",
  "Roraima": "BR",
  "Santa Catarina": "BR",
  "São Paulo": "BR",
  "Sergipe": "BR",
  "Tocantins": "BR",

  // Australia
  "Australian Capital Territory": "AU",
  "New South Wales": "AU",
  "Northern Territory": "AU",
  "Queensland": "AU",
  "South Australia": "AU",
  "Tasmania": "AU",
  "Victoria": "AU",
  "Western Australia": "AU",

  // Mexico
  "Aguascalientes": "MX",
  "Baja California": "MX",
  "Baja California Sur": "MX",
  "Campeche": "MX",
  "Chiapas": "MX",
  "Chihuahua": "MX",
  "Mexico City": "MX",
  "Coahuila": "MX",
  "Colima": "MX",
  "Durango": "MX",
  "Guanajuato": "MX",
  "Guerrero": "MX",
  "Hidalgo": "MX",
  "Jalisco": "MX",
  "State of Mexico": "MX",
  "Michoacán": "MX",
  "Morelos": "MX",
  "Nayarit": "MX",
  "Nuevo León": "MX",
  "Oaxaca": "MX",
  "Puebla": "MX",
  "Querétaro": "MX",
  "Quintana Roo": "MX",
  "San Luis Potosí": "MX",
  "Sinaloa": "MX",
  "Sonora": "MX",
  "Tabasco": "MX",
  "Tamaulipas": "MX",
  "Tlaxcala": "MX",
  "Veracruz": "MX",
  "Yucatán": "MX",
  "Zacatecas": "MX",

  // Switzerland
  "Aargau": "CH",
  "Appenzell Innerrhoden": "CH",
  "Appenzell Ausserrhoden": "CH",
  "Basel-Stadt": "CH",
  "Basel-Landschaft": "CH",
  "Bern": "CH",
  "Fribourg": "CH",
  "Geneva": "CH",
  "Glarus": "CH",
  "Graubünden": "CH",
  "Jura": "CH",
  "Lucerne": "CH",
  "Neuchâtel": "CH",
  "Nidwalden": "CH",
  "Obwalden": "CH",
  "Schaffhausen": "CH",
  "Schwyz": "CH",
  "Solothurn": "CH",
  "St. Gallen": "CH",
  "Thurgau": "CH",
  "Ticino": "CH",
  "Uri": "CH",
  "Valais": "CH",
  "Vaud": "CH",
  "Zug": "CH",
  "Zurich": "CH",

  // India
  "Andhra Pradesh": "IN",
  "Arunachal Pradesh": "IN",
  "Assam": "IN",
  "Bihar": "IN",
  "Chhattisgarh": "IN",
  "Goa": "IN",
  "Gujarat": "IN",
  "Haryana": "IN",
  "Himachal Pradesh": "IN",
  "Jharkhand": "IN",
  "Karnataka": "IN",
  "Kerala": "IN",
  "Madhya Pradesh": "IN",
  "Maharashtra": "IN",
  "Manipur": "IN",
  "Meghalaya": "IN",
  "Mizoram": "IN",
  "Nagaland": "IN",
  "Odisha": "IN",
  "Punjab": "IN",
  "Rajasthan": "IN",
  "Sikkim": "IN",
  "Tamil Nadu": "IN",
  "Telangana": "IN",
  "Tripura": "IN",
  "Uttar Pradesh": "IN",
  "Uttarakhand": "IN",
  "West Bengal": "IN",

  // China
  "Anhui": "CN",
  "Beijing": "CN",
  "Chongqing": "CN",
  "Fujian": "CN",
  "Gansu": "CN",
  "Guangdong": "CN",
  "Guangxi": "CN",
  "Guizhou": "CN",
  "Hainan": "CN",
  "Hebei": "CN",
  "Heilongjiang": "CN",
  "Henan": "CN",
  "Hong Kong": "CN",
  "Hubei": "CN",
  "Hunan": "CN",
  "Inner Mongolia": "CN",
  "Jiangsu": "CN",
  "Jiangxi": "CN",
  "Jilin": "CN",
  "Liaoning": "CN",
  "Macau": "CN",
  "Ningxia": "CN",
  "Qinghai": "CN",
  "Shaanxi": "CN",
  "Shandong": "CN",
  "Shanghai": "CN",
  "Shanxi": "CN",
  "Sichuan": "CN",
  "Taiwan": "CN",
  "Tibet": "CN",
  "Tianjin": "CN",
  "Xinjiang": "CN",
  "Yunnan": "CN",
  "Zhejiang": "CN",

  // Russia
  "Moscow": "RU",
  "Saint Petersburg": "RU",

  // Tanzania
  "Zanzibar": "TZ",

  // Portugal
  "Azores": "PT",
  "Madeira": "PT",

  // France overseas
  "Réunion": "FR",
};

/**
 * Mapping from country names (as used in flags_complete.json) to ISO 3166-1 alpha-2 codes
 */
export const countryNameToISOCode: Record<string, string> = {
  // Africa
  "Angola": "AO",
  "Benin": "BJ",
  "Botswana": "BW",
  "Burkina Faso": "BF",
  "Burundi": "BI",
  "Cameroon": "CM",
  "Cape Verde": "CV",
  "Central African Republic": "CF",
  "Chad": "TD",
  "Comoros": "KM",
  "Congo": "CG",
  "Democratic Republic of the Congo": "CD",
  "Republic of the Congo": "CG",
  "Côte d'Ivoire": "CI",
  "Djibouti": "DJ",
  "Egypt": "EG",
  "Equatorial Guinea": "GQ",
  "Eritrea": "ER",
  "Eswatini": "SZ",
  "Ethiopia": "ET",
  "Gabon": "GA",
  "Gambia": "GM",
  "Ghana": "GH",
  "Guinea": "GN",
  "Guinea-Bissau": "GW",
  "Kenya": "KE",
  "Lesotho": "LS",
  "Liberia": "LR",
  "Libya": "LY",
  "Madagascar": "MG",
  "Malawi": "MW",
  "Mali": "ML",
  "Mauritania": "MR",
  "Mauritius": "MU",
  "Morocco": "MA",
  "Mozambique": "MZ",
  "Namibia": "NA",
  "Niger": "NE",
  "Nigeria": "NG",
  "Rwanda": "RW",
  "São Tomé and Príncipe": "ST",
  "Senegal": "SN",
  "Seychelles": "SC",
  "Sierra Leone": "SL",
  "Somalia": "SO",
  "South Africa": "ZA",
  "South Sudan": "SS",
  "Sudan": "SD",
  "Tanzania": "TZ",
  "Togo": "TG",
  "Tunisia": "TN",
  "Uganda": "UG",
  "Zambia": "ZM",
  "Zimbabwe": "ZW",

  // Asia
  "Afghanistan": "AF",
  "Armenia": "AM",
  "Azerbaijan": "AZ",
  "Bahrain": "BH",
  "Bangladesh": "BD",
  "Bhutan": "BT",
  "Brunei": "BN",
  "Cambodia": "KH",
  "China": "CN",
  "Georgia": "GE",
  "Hong Kong": "HK",
  "India": "IN",
  "Indonesia": "ID",
  "Iran": "IR",
  "Iraq": "IQ",
  "Israel": "IL",
  "Japan": "JP",
  "Jordan": "JO",
  "Kazakhstan": "KZ",
  "Kuwait": "KW",
  "Kyrgyzstan": "KG",
  "Laos": "LA",
  "Lebanon": "LB",
  "Macao": "MO",
  "Malaysia": "MY",
  "Maldives": "MV",
  "Mongolia": "MN",
  "Myanmar": "MM",
  "Nepal": "NP",
  "North Korea": "KP",
  "Oman": "OM",
  "Pakistan": "PK",
  "Palestine": "PS",
  "Philippines": "PH",
  "Qatar": "QA",
  "Saudi Arabia": "SA",
  "Singapore": "SG",
  "South Korea": "KR",
  "Sri Lanka": "LK",
  "Syria": "SY",
  "Taiwan": "TW",
  "Tajikistan": "TJ",
  "Thailand": "TH",
  "Timor-Leste": "TL",
  "Turkey": "TR",
  "Turkmenistan": "TM",
  "United Arab Emirates": "AE",
  "Uzbekistan": "UZ",
  "Vietnam": "VN",
  "West Bank": "PS",
  "Yemen": "YE",

  // Europe
  "Albania": "AL",
  "Andorra": "AD",
  "Austria": "AT",
  "Belarus": "BY",
  "Belgium": "BE",
  "Bosnia and Herzegovina": "BA",
  "Bulgaria": "BG",
  "Croatia": "HR",
  "Cyprus": "CY",
  "Czech Republic": "CZ",
  "Czechia": "CZ",
  "Denmark": "DK",
  "Estonia": "EE",
  "Finland": "FI",
  "France": "FR",
  "Germany": "DE",
  "Greece": "GR",
  "Hungary": "HU",
  "Iceland": "IS",
  "Ireland": "IE",
  "Italy": "IT",
  "Kosovo": "XK",
  "Latvia": "LV",
  "Liechtenstein": "LI",
  "Lithuania": "LT",
  "Luxembourg": "LU",
  "Macedonia": "MK",
  "Malta": "MT",
  "Moldova": "MD",
  "Monaco": "MC",
  "Montenegro": "ME",
  "Netherlands": "NL",
  "North Macedonia": "MK",
  "Norway": "NO",
  "Poland": "PL",
  "Portugal": "PT",
  "Romania": "RO",
  "Russia": "RU",
  "San Marino": "SM",
  "Serbia": "RS",
  "Slovakia": "SK",
  "Slovenia": "SI",
  "Spain": "ES",
  "Sweden": "SE",
  "Switzerland": "CH",
  "Ukraine": "UA",
  "United Kingdom": "GB",

  // North America
  "Antigua and Barbuda": "AG",
  "Bahamas": "BS",
  "Barbados": "BB",
  "Belize": "BZ",
  "Canada": "CA",
  "Costa Rica": "CR",
  "Cuba": "CU",
  "Dominica": "DM",
  "Dominican Republic": "DO",
  "El Salvador": "SV",
  "Grenada": "GD",
  "Guatemala": "GT",
  "Haiti": "HT",
  "Honduras": "HN",
  "Jamaica": "JM",
  "Mexico": "MX",
  "Nicaragua": "NI",
  "Panama": "PA",
  "Saint Kitts and Nevis": "KN",
  "Saint Lucia": "LC",
  "Saint Vincent and the Grenadines": "VC",
  "Trinidad and Tobago": "TT",
  "United States": "US",

  // South America
  "Argentina": "AR",
  "Bolivia": "BO",
  "Brazil": "BR",
  "Chile": "CL",
  "Colombia": "CO",
  "Ecuador": "EC",
  "Guyana": "GY",
  "Paraguay": "PY",
  "Peru": "PE",
  "Suriname": "SR",
  "Uruguay": "UY",
  "Venezuela": "VE",

  // Oceania
  "Australia": "AU",
  "Fiji": "FJ",
  "Kiribati": "KI",
  "Marshall Islands": "MH",
  "Micronesia": "FM",
  "Nauru": "NR",
  "New Zealand": "NZ",
  "Palau": "PW",
  "Papua New Guinea": "PG",
  "Samoa": "WS",
  "Solomon Islands": "SB",
  "Tonga": "TO",
  "Tuvalu": "TV",
  "Vanuatu": "VU",
};
